"""add provider and price tables

Revision ID: 8ba9b2a94d20
Revises: 591ee1dcfc77
Create Date: 2026-05-19 17:21:33.897271

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ba9b2a94d20'
down_revision: Union[str, Sequence[str], None] = '591ee1dcfc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=True)
    op.create_table('latest_prices',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_latest_price_asset')
    )
    op.create_table('price_snapshots',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_asset_id'), 'price_snapshots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_provider_id'), 'price_snapshots', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_snapshots_provider_id'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_asset_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('latest_prices')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
