#!/bin/bash
# One-Paste Deployment Script for Novax Price Alert
# Copy this entire script, paste it into your terminal, and it will guide you through deployment

echo "🚀 Novax Price Alert - One-Paste Deployment Guide"
echo "==================================================="
echo ""
echo "VPS: 193.93.169.58 (ubuntu)"
echo "Password: ArAd@#!23662366"
echo "Domain: novax.alirezasafeidev.ir"
echo "Bot ID: 8858674032 (@novax_price_bot)"
echo ""
echo "Please follow these steps:"
echo ""
echo "Step 1: SSH to VPS"
echo "--------------------------------------"
echo "Run this command in your terminal:"
echo ""
echo "ssh ubuntu@193.93.169.58"
echo ""
echo "When prompted, enter password: ArAd@#!23662366"
echo ""
echo "Step 2: Navigate to app directory"
echo "--------------------------------------"
echo ""
echo "cd /home/deploy/novax-price-alert"
echo ""
echo "Step 3: Check if directory exists"
echo "--------------------------------------"
echo ""
echo "ls -la"
echo ""
echo "Step 4: Sync files (from your LOCAL machine, NOT VPS)"
echo "--------------------------------------"
echo "Open a NEW terminal on your local machine and run:"
echo ""
echo "cd /home/dev13/my-project/sites/secondary/novax-price-alert"
echo ""
echo "rsync -avz --delete \\"
echo "  --exclude='.git' \\"
echo "  --exclude='__pycache__' \\"
echo "  --exclude='*.pyc' \\"
echo "  --exclude='.venv' \\"
echo "  --exclude='node_modules' \\"
echo "  --exclude='.next' \\"
echo "  --exclude='dist' \\"
echo "  --exclude='deploy/cloudflare-worker' \\"
echo "  . \\"
echo "  ubuntu@193.93.169.58:/home/deploy/novax-price-alert/"
echo ""
echo "Step 5: Install dependencies (on VPS)"
echo "--------------------------------------"
echo ""
echo "python3 -m pip install --upgrade pip"
echo "python3 -m pip install -r requirements.txt"
echo ""
echo "Step 6: Build mini-app (on VPS)"
echo "--------------------------------------"
echo ""
echo "cd mini-app"
echo "npm install"
echo "npm run build"
echo "cd .."
echo ""
echo "Step 7: Database migrations (on VPS)"
echo "--------------------------------------"
echo ""
echo "alembic upgrade head"
echo ""
echo "Step 8: Configure .env for VPS-only (on VPS)"
echo "--------------------------------------"
echo ""
echo "nano .env"
echo "# Find and edit these lines:"
echo "# TELEGRAM_RELAY_URL=  (leave empty)"
echo "# TELEGRAM_RELAY_SECRET=  (leave empty)"
echo "# Save with Ctrl+X, Y, Enter"
echo ""
echo "Step 9: Restart PM2 (on VPS)"
echo "--------------------------------------"
echo ""
echo "pm2 restart novax-api --update-env"
echo "pm2 restart novax-worker --update-env"
echo "pm2 restart novax-mini-app --update-env"
echo "pm2 save"
echo ""
echo "Step 10: Check status (on VPS)"
echo "--------------------------------------"
echo ""
echo "pm2 status"
echo ""
echo "Step 11: Health checks (on VPS)"
echo "--------------------------------------"
echo ""
echo "curl http://127.0.0.1:8001/health"
echo "curl http://127.0.0.1:8001/api/v1/prices/latest"
echo "curl https://novax.alirezasafeidev.ir/health"
echo ""
echo "Step 12: Test bot (in Telegram)"
echo "--------------------------------------"
echo ""
echo "1. Open Telegram"
echo "2. Search: @novax_price_bot"
echo "3. Send /start"
echo "4. Send /price"
echo "5. Try creating an alert"
echo ""
echo "==================================================="
echo "✅ That's it! Your bot should be live."
echo "==================================================="
echo ""
echo "If you need help, check:"
echo "  docs/DEPLOYMENT_GUIDE.md"
echo "  docs/BOTFATHER_SETUP.md"
echo ""