#!/bin/bash

# Manual Deployment Instructions for Novax Price Alert
# VPS: 193.93.169.58
# Bot ID: 8858674032 (@novax_price_bot)

echo "🚀 Novax Price Alert - Manual Deployment Guide"
echo "================================================"
echo ""
echo "⚠️  NOTE: This script provides instructions for manual deployment"
echo "⚠️  Automated deployment requires sshpass installation"
echo ""
echo "📋 VPS Information:"
echo "   IP: 193.93.169.58"
echo "   User: ubuntu"
echo "   Password: ArAd@#!23662366"
echo "   Domain: novax.alirezasafeidev.ir"
echo ""
echo "🤖 Bot ID: 8858674032 (@novax_price_bot)"
echo ""

echo "📝 Step-by-Step Manual Deployment:"
echo "=================================="
echo ""
echo "1. Install sshpass on your local machine:"
echo "   sudo apt-get update"
echo "   sudo apt-get install -y sshpass"
echo ""
echo "2. Then run the automated deployment:"
echo "   cd /home/dev13/my-project/sites/secondary/novax-price-alert"
echo "   ./scripts/deploy-vps-only.sh"
echo ""
echo "OR manually deploy with these steps:"
echo "==================================="
echo ""
echo "1. SSH to VPS:"
echo "   ssh ubuntu@193.93.169.58"
echo "   (password: ArAd@#!23662366)"
echo ""
echo "2. Navigate to app directory:"
echo "   cd /home/deploy/novax-price-alert"
echo ""
echo "3. Sync files from local to VPS (from local machine):"
echo "   rsync -avz --delete \\"
echo "     --exclude='.git' \\"
echo "     --exclude='__pycache__' \\"
echo "     --exclude='*.pyc' \\"
echo "     --exclude='.venv' \\"
echo "     --exclude='node_modules' \\"
echo "     --exclude='.next' \\"
echo "     --exclude='dist' \\"
echo "     --exclude='deploy/cloudflare-worker' \\"
echo "     . \\"
echo "     ubuntu@193.93.169.58:/home/deploy/novax-price-alert/"
echo ""
echo "4. On VPS, install Python dependencies:"
echo "   python3 -m pip install --upgrade pip"
echo "   python3 -m pip install -r requirements.txt"
echo ""
echo "5. Build mini-app:"
echo "   cd mini-app"
echo "   npm install"
echo "   npm run build"
echo "   cd .."
echo ""
echo "6. Run database migrations:"
echo "   alembic upgrade head"
echo ""
echo "7. Configure .env for VPS-only mode:"
echo "   Edit .env and set:"
echo "   TELEGRAM_RELAY_URL="
echo "   TELEGRAM_RELAY_SECRET="
echo ""
echo "8. Restart PM2 services:"
echo "   pm2 restart novax-api --update-env"
echo "   pm2 restart novax-worker --update-env"
echo "   pm2 restart novax-mini-app --update-env"
echo "   pm2 save"
echo ""
echo "9. Check PM2 status:"
echo "   pm2 status"
echo ""
echo "10. Health checks:"
echo "   curl http://127.0.0.1:8001/health"
echo "   curl http://127.0.0.1:8001/api/v1/prices/latest"
echo "   curl https://novax.alirezasafeidev.ir/health"
echo ""
echo "11. Test bot:"
echo "   Open Telegram"
echo "   Find @novax_price_bot"
echo "   Send /start"
echo "   Send /price"
echo "   Try creating an alert"
echo ""
echo "✅ Deployment complete!"
echo ""