#!/bin/bash
# Quick Sync Script - Sync latest changes to VPS
# This will sync only the new files that weren't in the previous deployment

echo "🔄 Syncing latest changes to VPS"
echo "=================================="
echo ""
echo "VPS: ubuntu@193.93.169.58"
echo "Path: /home/ubuntu/novax-price-alert"
echo ""

echo "Latest local commit:"
git log --oneline -1
echo ""

echo "New files to sync:"
echo "  - docs/BOTFATHER_SETUP.md"
echo "  - docs/CODE_REALITY_REPORT.md"
echo "  - docs/DEPLOYMENT_ARCHITECTURE.md"
echo "  - docs/DEPLOYMENT_GUIDE.md"
echo "  - docs/DEPLOYMENT_SUMMARY.md"
echo "  - docs/QUICK_REFERENCE.md"
echo "  - docs/SERVER_STATUS.md"
echo "  - docs/PREMIUM_FEATURES_PLAN.md"
echo "  - docs/WORK_SUMMARY.md"
echo "  - scripts/deploy-to-vps.sh"
echo "  - scripts/deploy-vps-only.sh"
echo "  - scripts/deploy-ssh.sh"
echo "  - scripts/deploy-plan.py"
echo "  - scripts/deploy-python.py"
echo "  - scripts/DEPLOY_NOW.sh"
echo "  - scripts/manual-deploy-guide.sh"
echo "  - scripts/test-vps-connection.sh"
echo "  - scripts/local-quality-check.sh"
echo "  - scripts/monitor-health.sh"
echo "  - LIVE_STATUS.md"
echo "  - .github/workflows/health-check-monitor.yml (fixed)"
echo ""

echo "Step 1: Sync files to VPS"
echo "--------------------------------"
echo "Run this command from your LOCAL machine:"
echo ""
echo "rsync -avz \\"
echo "  --exclude='.git' \\"
echo "  --exclude='__pycache__' \\"
echo "  --exclude='*.pyc' \\"
echo "  --exclude='.venv' \\"
echo "  --exclude='node_modules' \\"
echo "  --exclude='.next' \\"
echo "  --exclude='dist' \\"
echo "  --exclude='deploy/cloudflare-worker' \\"
echo "  . \\"
echo "  ubuntu@193.93.169.58:/home/ubuntu/novax-price-alert/"
echo ""

echo "Step 2: SSH to VPS"
echo "--------------------------------"
echo "ssh ubuntu@193.93.169.58"
echo "cd /home/ubuntu/novax-price-alert"
echo ""

echo "Step 3: No restart needed"
echo "--------------------------------"
echo "These changes are only documentation and scripts."
echo "No restart of services is required."
echo ""

echo "Step 4: Verify sync"
echo "--------------------------------"
echo "ls -la docs/"
echo "ls -la scripts/"
echo ""

echo "✅ That's it! Changes synced."
echo ""
echo "Note: The main code (Python, API) hasn't changed."
echo "Only documentation and deployment scripts were added."
echo "Production services continue to run normally."